[package]
name = "guis"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.13.1"
time = {version = "0.3.0-alpha-2", features = ["local-offset"] }